### PR TITLE
Add support for ARM64

### LINKED ISSUE #597: Not able to install natively on Apple M1
I'm just trying Owl and couldn't get this to compile natively on a M1 Mac.
If you use the rosetta emulation on the Mac you can get a working system.

I used:
sudo arch -x86_64 before the rest of the "opam/master/shell/install.sh" command. Then opam just works for the full owl install. The other awkward thing is to put arch -x86_64 before all the brew installs eg plplot openblas etc.

### PR DESCRIPTION
**Pull request by mseri**
Thanks @jhgorse for the help!
Should fix #597, I tested this on an iMac M1 and my Macbook Pro, but it would be good if somebody else could test it as well.

### CODE REVIEW

**Comment by mseri** [comment]
A parallel PR is needed for `eigen`, to remove `-march=native` or to detect it during build like we are doing here

**Comment by ryanrhymes** [comment]
Awesome, looks very good to me.

**Review by ryanrhymes — APPROVED** [review]

**Comment by ryanrhymes** [comment]
@jzstark can you also test on your mac?

**Comment by xinslu** [comment]
Sorry, I wasn't pinged but I tried it out and it works on my MacBook Air M1 2020.

**Comment by ddph3dg** [comment]
I still can't get this install to work. I needed to set the EIGEN_FLAGS to get eigen installed but fail with a ld error on owl:
ld: file not found: @rpath/libgcc_s.1.1.dylib for architecture arm64
It seems everything compiles OK but there is a hardcoded reference. A quick search seems to indicate openBlas gets compiled with this somehow.

**Comment by mseri** [comment]
Having to set `EIGEN_FLAGS` is expected, the architecture detection has not been ported to eigen yet.

The error you get seems related to a mix of rosetta x86 libraries and arm64 in the system, `@rpath` is the runpath for macos dynamic linker.

**Pull request merged**
