### PR TITLE
Signal

### PR DESCRIPTION
**Pull request by kumanna**
This is our initial attempt to address issue #564.

### CODE REVIEW

**Review by mseri — COMMENTED** [review]
Fantastic! Can you add `owl_signal.mli` with the interface to expose and the corresponding documentation?

**Review by ryanrhymes — APPROVED** [review]

**Comment by ryanrhymes** [comment]
Great work! As @mseri commented, it would be great to have an mli file.

**Review by tachukao — COMMENTED** [review]
Looks great! thanks for the PR.

**Comment by kumanna** [comment]
Please do verify the updates. We have altered the tests and added an MLI file. Happy to make changes as needed.

Thanks.

**Comment by ryanrhymes** [comment]
Looks very good to me. @mseri comments?

**Comment by jzstark** [comment]
Looks great to me. I would suggest extending this module to both single and double precision, but that can be revised in a future PR.

**Review by mseri — APPROVED** [review]
Looks good. Thanks for the changes.
I fully agree with @jzstark

**Pull request merged**
