### PR TITLE
added get_fancy amd set_fancy to the algodiff library

### PR DESCRIPTION
**Pull request by tachukao**
In this PR, I added `get_fancy` and `set_fancy` to Algodiff. 

I've also added unit tests for `get_slice` and `get_fancy`.

### CODE REVIEW

**Comment by ghennequin** [comment]
I have reviewed this, looks all good! Thanks @tachukao :100:

**Review by mseri — APPROVED** [review]
🎉

**Comment by mseri** [comment]
Are the indentation changes related to the other ocamlformat PR?

**Comment by ryanrhymes** [comment]
Oh this is awesome!

**Comment by tachukao** [comment]
Not sure about the indentation changes. I'm currently still on ocamlformat 0.15.0 and that might be why...

**Comment by mseri** [comment]
Fwiw I don’t mind those, and I believe they have been reverted to this. Ithink this should be merged.

**Comment by ryanrhymes** [comment]
Yes I agree. CI failed, but it looks like docker hub issue?

**Comment by mseri** [comment]
Yes, it is a general problem, not just owl. somebody is already working on it afaik

**Pull request merged**
