### PR TITLE
Merged tests for different AD operations into one big test + autoformat tests with ocamlformat

### PR DESCRIPTION
**Pull request by tachukao**
- Merged tests for different AD operations into one big unit test. Custom error message shows which operations failed (as discussed in #467)
- Use ocamlformat to autformat all the unit tests

### CODE REVIEW

**Comment by tachukao** [comment]
turns out the log is still too long for travis...probably need to do a similar thing for other test sets

**Comment by tachukao** [comment]
@jzstark I've chosen to make wrap the elements of the list in the latest commit because otherwise you get files like this

https://github.com/tachukao/owl/blob/6cd62ddcdab29f5f67da537be2d4e0e4df342bb1/test/unit_ndarray_core_generic.ml#L306

as opposed to this

https://github.com/tachukao/owl/blob/34c0768572d73f24431297415c640faa1f4d6b96/test/unit_ndarray_core_generic.ml#L275

But yea I agree squashing several tests into one line isn't ideal

**Comment by ryanrhymes** [comment]
@jzstark @tachukao the developers of ocamlformat are very cooperative, so just fire issues on their repo to ask if they can help anything. There are some issues but overall I think ocamlformat is a good solution and in the long run, I think Owl should switch to this tool completely. So we can give them feedback to make ocamlformat better.

**Comment by mseri** [comment]
Does setting ALCOTEST_COMPACT in the travis env to true or 1 help concerning the tests verbosity?

**Comment by tachukao** [comment]
@ryanrhymes made an issue request here https://github.com/ocaml-ppx/ocamlformat/issues/1176

**Comment by ryanrhymes** [comment]
> Does setting ALCOTEST_COMPACT in the travis env to true or 1 help concerning the tests verbosity?

We definily need to try this.

**Comment by ryanrhymes** [comment]
> @ryanrhymes made a feature request here [ocaml-ppx/ocamlformat#1176](https://github.com/ocaml-ppx/ocamlformat/issues/1176)

Great, thanks! I think it is OK to merge, let's refine the format later in other PRs, esp if ocamlformat can implement that feature.

**Comment by ryanrhymes** [comment]
@jzstark similar to Calvin's ocaml-ppx/ocamlformat#1176 you can also fire one issue w.r.t single line function clutting togher on camlformat repo?

**Comment by jzstark** [comment]
Done. Just make a similar request issue [here](https://github.com/ocaml-ppx/ocamlformat/issues/1177).  These features would indeed be quite helpful to Owl code.

**Pull request merged**
