### PR TITLE
Draw poisson RVs in Ndarray and Mat modules

### PR DESCRIPTION
**Pull request by tachukao**
I added a function to draw samples from a poisson distribution with rate `mu`
```ocaml
val poisson : mu:float -> int array -> Arr.arr
```
Here, I have not implemented the option to provide a `mu` of type `Arr.arr`, as suggested in #496.  

Perhaps, as future extensions,  for each the random variable functions `gaussian`, `uniform` and `poisson`, we could add the variants:

```ocaml
val gaussian_rvs : mu:Arr.arr -> sigma:Arr.arr -> int array -> Arr.arr
val uniform_rvs : a:Arr.arr -> b:Arr.arr -> int array -> Arr.arr
val poisson_rvs: mu:Arr.arr -> int array -> Arr.arr
```

where parameters `mu`, `sigma`, `a`, and `b` are broadcasted to the requested shape.

For `gaussian_rvs`, this could already easily implemented:

```ocaml
let gaussian_rvs ~mu ~sigma dims =
     mu + (sigma * (gaussian dims))
```

### CODE REVIEW

**Comment by ryanrhymes** [comment]
fyi, if you need more flexible parameterisation, you can consider https://github.com/owlbarn/owl/blob/master/src/owl/ppl/owl_distribution.mli

**Comment by tachukao** [comment]
Oh cool! this looks super useful. Is the `Owl_distribution` module readily _made_ anywhere? 

I'll try and add a `Poisson` module to this in the coming days. This looks great

**Comment by ryanrhymes** [comment]
This module was orignally designed to serve PPL, but PPL progress was stalled. But this year, there are two Part II students working on PPL atop of owl, let's see what they will bring to us :)

The module interface borrows the design of corresponding module in TensorFlow. It is not used by any other modules atm, actually few people know this module.

**Comment by ryanrhymes** [comment]
feel free to tinker it and PR :)

**Comment by tachukao** [comment]
I think for general use, the functions in `Owl_distribution_generic` are already very useful, and could in principle be directly included in the `Ndarray` modules? what do you think?

**Comment by ryanrhymes** [comment]
might make ndarray interface very heavy, but let see what others @mseri @jzstark think ...

**Comment by mseri** [comment]
I agree with @ryanrhymes, it is better to have easy to find specific modules imho than massive ones. We also benefit from link time cleanups from the compiler removing all the unused modules from the produced artifacts

**Comment by tachukao** [comment]
yea actually I agree. it's probably best kept separate. Plus, `Owl_distribution` seems to depend on the dense `Ndarray` module already

**Comment by jzstark** [comment]
Agree. It's useful to add some standard distribution such as gaussian/poisson/uniform in ndarray  module, but perhaps it goes too far to move all of them into ndarray. Adding parameters to these distributions sounds a good idea. Also, perhaps we should consider adding it in the base library later if a poisson distribution is indeed frequently used.

**Pull request merged**
