### PR TITLE
Windows installation doc

### PR DESCRIPTION
**Pull request by kkirstein**
I have updated the installation docs for PLplot on Windows. Unfortunately, it is quite a hack, as cross-compiling PLplot seems not to work for the Cygwin/Mingw combination.
Anyway, if I remember correctly, last time there was a suggestions to merge these instructions into the main README.
Personally, I would prefer to keep it separate, but of course, that's up to the maintainers. Alternatively, these instructions might also be included in the [Owl book](https://ocaml.xyz/book/).
Please feel free to give feedback, if something is unclear.

### CODE REVIEW

**Review by jzstark — APPROVED** [review]

**Comment by kkirstein** [comment]
In the meantime I got some valuable input from the PLplot developers, on how to fix the build issues. Please find the updated instructions now.

**Review by ryanrhymes — APPROVED** [review]

**Review by mseri — APPROVED** [review]
Wow! Thanks a lot

**Comment by kkirstein** [comment]
In the meantime, the issue with `pkg-config`has been fixed (https://github.com/fdopen/opam-repository-mingw/issues/96), but I will leave the workaround in, as not everybody might update their OCaml/Windows toolchain so regularly.

**Comment by mseri** [comment]
What is preventing this PR to be merged? @jzstark @ryanrhymes

**Comment by jzstark** [comment]
So sorry for the late reply! Me and Liang have been really busy with other projects recently. This PR looks great and I'll soon merge it.

**Pull request merged**
