### PR TITLE
changes to algodiff tests + bug in algodiff concatenate

### PR DESCRIPTION
**Pull request by tachukao**
- fixed bug in the implementation of `concatenate` in Algodiff
- some changes which hopefully make the algodiff tests for `sylvester` and `discrete_lyapunov` more stable

### CODE REVIEW

**Comment by tachukao** [comment]
To improve finite difference approximations of reverse-mode gradients, in the latest commit, I've added the option to use a fourth-order approximation. Hopefully this will help reduce random algodiff test failures referenced in #460 and other places.

**Comment by mseri** [comment]
Can we make the tests quieter and show on,y the failing tests if any?

**Comment by tachukao** [comment]
Good idea, I’ll give it a go

**Comment by jzstark** [comment]
BTW, just wondering why the commits are not squashed...AFAIK that's kind of a common practice in PR.

**Comment by mseri** [comment]
In most of the project I work on we squash only unclean histories. If the commit tree is clean as it should be and as it is in this case it is good to have a breakdown of what each commit fixes/does.

**Pull request merged**
