### PR TITLE
Split out plplot

### PR DESCRIPTION
**Pull request by mseri**
This should help for https://github.com/owlbarn/owl/issues/377

### CODE REVIEW

**Comment by ryanrhymes** [comment]
Thank you Marcello, shall we also add the plplot dependency into owl-top. It is better to have 'hub' lib which loads everything for users, in order to give them a relatively complete environment.

**Comment by ryanrhymes** [comment]
btw, I moved the plplot folder into src which also includes all other sub libs.

**Comment by mseri** [comment]
Do you want me to send a separate pr for the owl-top thing or you'll deal with it?

**Comment by ryanrhymes** [comment]
yes, a PR would be nice, thanks 👍

**Pull request merged**
